#!/usr/bin/env bash
#
# test-api.sh
# Integration tests for office-converter HTTP API.
#
# Requires:
#   - Running server (see run-integration-tests.sh)
#   - curl, python3 (for JSON handling when jq missing)
#   - testdata/sample.xlsx and sample.ods (generated by generate-samples.sh)
#   - Optional: testdata/sample.xlsb for full xlsb coverage
#
# Usage:
#   SERVER_URL=http://localhost:8080 ./scripts/test-api.sh
#   ./scripts/test-api.sh --help
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TESTDATA_DIR="$ROOT_DIR/testdata"

SERVER_URL="${SERVER_URL:-http://localhost:8080}"
VERBOSE="${VERBOSE:-0}"

# Colors
if [[ -t 1 ]]; then
  RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BLUE=$'\033[34m'; RESET=$'\033[0m'
else
  RED=""; GREEN=""; YELLOW=""; BLUE=""; RESET=""
fi

TOTAL=0; PASSED=0; FAILED=0; SKIPPED=0
WORK_DIR="$(mktemp -d -t xlsb-test-XXXXXX)"
trap 'rm -rf "$WORK_DIR"' EXIT

log() { echo "$*" >&2; }
info() { echo "${BLUE}INFO${RESET} $*"; }
pass() { echo "${GREEN}PASS${RESET} $*"; PASSED=$((PASSED + 1)); }
fail() { echo "${RED}FAIL${RESET} $*"; FAILED=$((FAILED + 1)); }
skip() { echo "${YELLOW}SKIP${RESET} $*"; SKIPPED=$((SKIPPED + 1)); }

die() { echo "${RED}FATAL${RESET} $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

require_cmd curl
require_cmd python3

has_jq=0
command -v jq >/dev/null 2>&1 && has_jq=1

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  -h, --help          Show this help
  --url URL           Server base URL (default: http://localhost:8080)
  --verbose           Show curl commands and bodies on failure

Environment:
  SERVER_URL          Same as --url
  VERBOSE=1           Enable verbose output
  SKIP_XLSB=1         Force skip all .xlsb tests even if sample exists

Samples are loaded from:
  $TESTDATA_DIR/sample.xlsx
  $TESTDATA_DIR/sample.ods
  $TESTDATA_DIR/sample.xlsb   (optional)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --url) SERVER_URL="$2"; shift 2 ;;
    --verbose) VERBOSE=1; shift ;;
    *) die "Unknown arg: $1" ;;
  esac
done

# --- Helpers -----------------------------------------------------------------

http_status() {
  # $1 = extra curl args...  (we always add -sS -w '%{http_code}' -o "$WORK_DIR/body")
  local out
  out=$(curl -sS -w '%{http_code}' -o "$WORK_DIR/body" "$@")
  echo "$out"
}

http_status_to_file() {
  # Like above but save body to caller-provided path
  local dst="$1"; shift
  curl -sS -w '%{http_code}' -o "$dst" "$@"
}

json_get() {
  # $1=json file, $2=key (top level). Uses python (no jq dep).
  python3 -c '
import json, sys
data = json.load(open(sys.argv[1]))
key = sys.argv[2]
val = data.get(key, "")
if isinstance(val, (dict, list)):
  print(json.dumps(val))
else:
  print(val)
' "$1" "$2"
}

json_success() {
  [[ "$(json_get "$1" success)" == "True" || "$(json_get "$1" success)" == "true" ]]
}

base64_decode_to() {
  # $1=base64 string or file containing it (trailing newline from print is tolerated), $2=dest
  if [[ -f "$1" ]]; then
    python3 -c '
import base64, sys
src = open(sys.argv[1], "rb").read().strip()
open(sys.argv[2], "wb").write(base64.b64decode(src))
' "$1" "$2"
  else
    printf '%s' "$1" | base64 -d > "$2" 2>/dev/null || python3 -c 'import base64,sys; open(sys.argv[2],"wb").write(base64.b64decode(sys.argv[1]))' "$1" "$2"
  fi
}

assert_status() {
  local expected="$1"; local actual="$2"; local what="$3"
  TOTAL=$((TOTAL + 1))
  if [[ "$actual" == "$expected" ]]; then
    pass "$what (HTTP $actual)"
  else
    fail "$what (HTTP $actual, expected $expected)"
    if [[ "$VERBOSE" == "1" ]]; then
      echo "    body: $(cat "$WORK_DIR/body" | head -c 500)" >&2
    fi
  fi
}

assert_file_exists_nonempty() {
  local f="$1"; local what="$2"
  TOTAL=$((TOTAL + 1))
  if [[ -s "$f" ]]; then
    pass "$what ($(stat -c%s "$f" 2>/dev/null || wc -c <"$f") bytes)"
  else
    fail "$what (missing or empty: $f)"
  fi
}

assert_extension() {
  local name="$1"; local want="$2"; local what="$3"
  TOTAL=$((TOTAL + 1))
  if [[ "${name,,}" == *"$want" ]]; then
    pass "$what (filename ends with $want)"
  else
    fail "$what (got '$name', wanted *${want})"
  fi
}

# --- Preconditions -----------------------------------------------------------

if [[ ! -f "$TESTDATA_DIR/sample.xlsx" || ! -f "$TESTDATA_DIR/sample.ods" ]]; then
  die "Missing sample files. Run: ./scripts/generate-samples.sh"
fi

XLSB_FILE="$TESTDATA_DIR/sample.xlsb"
HAVE_XLSB=0
if [[ -f "$XLSB_FILE" && "${SKIP_XLSB:-0}" != "1" ]]; then
  HAVE_XLSB=1
fi

echo "==> Testing $SERVER_URL"
echo "    xlsx: $TESTDATA_DIR/sample.xlsx"
echo "    ods : $TESTDATA_DIR/sample.ods"
if [[ $HAVE_XLSB -eq 1 ]]; then
  echo "    xlsb: $XLSB_FILE"
else
  echo "    xlsb: (none - xlsb tests will be skipped)"
fi
echo

# --- 1. Health ---------------------------------------------------------------

info "Health checks"
status=$(http_status_to_file "$WORK_DIR/h.txt" "$SERVER_URL/healthz")
assert_status 200 "$status" "GET /healthz"

status=$(http_status_to_file "$WORK_DIR/h.txt" -I "$SERVER_URL/healthz")
assert_status 200 "$status" "HEAD /healthz"

# --- 2. Typed endpoints - multipart direct download --------------------------

info "Multipart direct download (typed endpoints)"

# xlsx -> ods
status=$(http_status_to_file "$WORK_DIR/out.ods" \
  -F "file=@$TESTDATA_DIR/sample.xlsx" \
  "$SERVER_URL/api/convert/xlsx-to-ods")
assert_status 200 "$status" "POST /api/convert/xlsx-to-ods (multipart)"
assert_file_exists_nonempty "$WORK_DIR/out.ods" "xlsx->ods direct download"
assert_extension "$(basename "$WORK_DIR/out.ods")" ".ods" "xlsx->ods output name"

# ods -> xlsx
status=$(http_status_to_file "$WORK_DIR/out.xlsx" \
  -F "file=@$TESTDATA_DIR/sample.ods" \
  "$SERVER_URL/api/convert/ods-to-xlsx")
assert_status 200 "$status" "POST /api/convert/ods-to-xlsx (multipart)"
assert_file_exists_nonempty "$WORK_DIR/out.xlsx" "ods->xlsx direct download"

# xlsb -> xlsx (if available)
if [[ $HAVE_XLSB -eq 1 ]]; then
  status=$(http_status_to_file "$WORK_DIR/out-from-xlsb.xlsx" \
    -F "file=@$XLSB_FILE" \
    "$SERVER_URL/api/convert/xlsb-to-xlsx")
  assert_status 200 "$status" "POST /api/convert/xlsb-to-xlsx (multipart)"
  assert_file_exists_nonempty "$WORK_DIR/out-from-xlsb.xlsx" "xlsb->xlsx direct download"
else
  skip "POST /api/convert/xlsb-to-xlsx (no sample.xlsb)"
fi

# --- 3. Smart endpoint (auto detect) - multipart -----------------------------

info "Smart endpoint /api/convert (multipart)"

status=$(http_status_to_file "$WORK_DIR/smart1.ods" \
  -F "file=@$TESTDATA_DIR/sample.xlsx" \
  "$SERVER_URL/api/convert")
assert_status 200 "$status" "smart: xlsx -> .ods"
assert_extension "$(basename "$WORK_DIR/smart1.ods")" ".ods" "smart xlsx output"

status=$(http_status_to_file "$WORK_DIR/smart2.xlsx" \
  -F "file=@$TESTDATA_DIR/sample.ods" \
  "$SERVER_URL/api/convert")
assert_status 200 "$status" "smart: ods -> .xlsx"
assert_extension "$(basename "$WORK_DIR/smart2.xlsx")" ".xlsx" "smart ods output"

if [[ $HAVE_XLSB -eq 1 ]]; then
  status=$(http_status_to_file "$WORK_DIR/smart3.xlsx" \
    -F "file=@$XLSB_FILE" \
    "$SERVER_URL/api/convert")
  assert_status 200 "$status" "smart: xlsb -> .xlsx"
  assert_extension "$(basename "$WORK_DIR/smart3.xlsx")" ".xlsx" "smart xlsb output"
else
  skip "smart xlsb (no sample.xlsb)"
fi

# --- 4. ?format=json on multipart --------------------------------------------

info "Multipart + ?format=json"

status=$(http_status_to_file "$WORK_DIR/json1.json" \
  -F "file=@$TESTDATA_DIR/sample.xlsx" \
  "$SERVER_URL/api/convert/xlsx-to-ods?format=json")
assert_status 200 "$status" "xlsx->ods ?format=json"
if json_success "$WORK_DIR/json1.json"; then
  pass "xlsx->ods json success=true"
  fn=$(json_get "$WORK_DIR/json1.json" filename)
  assert_extension "$fn" ".ods" "json filename field"
  # decode data and check size (do it in one python to avoid large-string subshell/fifo issues)
  python3 -c '
import json, base64, sys
d = json.load(open(sys.argv[1]))
raw = base64.b64decode(d["data"])
open(sys.argv[2], "wb").write(raw)
print("decoded", len(raw), "bytes")
' "$WORK_DIR/json1.json" "$WORK_DIR/decoded.ods"
  assert_file_exists_nonempty "$WORK_DIR/decoded.ods" "decoded data from json"
else
  fail "xlsx->ods json success was not true"
  [[ "$VERBOSE" == "1" ]] && cat "$WORK_DIR/json1.json" >&2
fi

# --- 5. Pure JSON API (base64) -----------------------------------------------

info "Pure JSON API (base64 input)"

# helper to build json body
make_json_body() {
  local file="$1"
  local b64
  b64=$(base64 -w0 < "$file")
  local name; name="$(basename "$file")"
  printf '{"file":"%s","filename":"%s"}' "$b64" "$name"
}

# xlsx -> ods via json
body=$(make_json_body "$TESTDATA_DIR/sample.xlsx")
status=$(printf '%s' "$body" | http_status_to_file "$WORK_DIR/j2.json" \
  -X POST -H "Content-Type: application/json" \
  -d @- \
  "$SERVER_URL/api/convert/xlsx-to-ods")
assert_status 200 "$status" "JSON xlsx->ods"
if json_success "$WORK_DIR/j2.json"; then
  pass "JSON xlsx->ods success"
else
  fail "JSON xlsx->ods not success"
fi

# ods -> xlsx via json
body=$(make_json_body "$TESTDATA_DIR/sample.ods")
status=$(printf '%s' "$body" | http_status_to_file "$WORK_DIR/j3.json" \
  -X POST -H "Content-Type: application/json" \
  -d @- \
  "$SERVER_URL/api/convert/ods-to-xlsx")
assert_status 200 "$status" "JSON ods->xlsx"

# smart via json (filename drives detection)
body=$(make_json_body "$TESTDATA_DIR/sample.xlsx")
status=$(printf '%s' "$body" | http_status_to_file "$WORK_DIR/j4.json" \
  -X POST -H "Content-Type: application/json" \
  -d @- \
  "$SERVER_URL/api/convert")
assert_status 200 "$status" "JSON smart xlsx->ods"

if [[ $HAVE_XLSB -eq 1 ]]; then
  body=$(make_json_body "$XLSB_FILE")
  status=$(printf '%s' "$body" | http_status_to_file "$WORK_DIR/j5.json" \
    -X POST -H "Content-Type: application/json" \
    -d @- \
    "$SERVER_URL/api/convert/xlsb-to-xlsx")
  assert_status 200 "$status" "JSON xlsb->xlsx"
else
  skip "JSON xlsb (no sample.xlsb)"
fi

# --- 6. Error cases ----------------------------------------------------------

info "Error handling"

# Wrong type on explicit route
status=$(http_status_to_file "$WORK_DIR/err1.json" \
  -F "file=@$TESTDATA_DIR/sample.xlsx" \
  "$SERVER_URL/api/convert/xlsb-to-xlsx")
assert_status 415 "$status" "xlsx sent to /xlsb-to-xlsx -> 415"

# Missing file field
status=$(http_status_to_file "$WORK_DIR/err2.json" \
  -F "notfile=@$TESTDATA_DIR/sample.xlsx" \
  "$SERVER_URL/api/convert")
assert_status 400 "$status" "missing 'file' field -> 400"

# Invalid base64 in JSON
status=$(printf '{"file":"!!!notbase64!!!","filename":"x.xlsx"}' | http_status_to_file "$WORK_DIR/err3.json" \
  -X POST -H "Content-Type: application/json" -d @- \
  "$SERVER_URL/api/convert/xlsx-to-ods")
assert_status 400 "$status" "invalid base64 -> 400"

# Unsupported format on smart
echo "hello" > "$WORK_DIR/notsheet.txt"
status=$(http_status_to_file "$WORK_DIR/err4.json" \
  -F "file=@$WORK_DIR/notsheet.txt" \
  "$SERVER_URL/api/convert")
assert_status 415 "$status" "unsupported extension on smart -> 415"

# JSON missing filename on smart
status=$(printf '{"file":"%s"}' "$(base64 -w0 < "$TESTDATA_DIR/sample.xlsx")" | http_status_to_file "$WORK_DIR/err5.json" \
  -X POST -H "Content-Type: application/json" -d @- \
  "$SERVER_URL/api/convert")
assert_status 400 "$status" "smart json without filename -> 400"

# --- 7. Content-Type on JSON responses ---------------------------------------

info "Content-Type verification (JSON responses)"

curl -sS -D "$WORK_DIR/hdr.txt" -o /dev/null -H "Accept: application/json" \
  -F "file=@$TESTDATA_DIR/sample.xlsx" \
  "$SERVER_URL/api/convert/xlsx-to-ods?format=json" 2>/dev/null || true
ct=$(awk -F': ' 'tolower($1) ~ /content-type/ {print tolower($2)}' "$WORK_DIR/hdr.txt" | tr -d '\r' | head -1)
TOTAL=$((TOTAL + 1))
if [[ "$ct" == *application/json* ]]; then
  pass "JSON response has application/json content-type"
else
  fail "JSON response content-type: $ct"
fi

# --- Summary -----------------------------------------------------------------

echo
echo "========================================"
echo "Results:"
echo "  TOTAL:   $TOTAL"
echo "  PASSED:  $PASSED"
echo "  FAILED:  $FAILED"
echo "  SKIPPED: $SKIPPED"
echo "========================================"

if [[ $FAILED -gt 0 ]]; then
  echo "${RED}Some tests failed.${RESET}"
  exit 1
fi
if [[ $PASSED -eq 0 ]]; then
  echo "${YELLOW}No tests ran?${RESET}"
  exit 1
fi
echo "${GREEN}All tests passed.${RESET}"
