// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FormatParam.
const (
	FormatParamJson FormatParam = "json"
)

// Valid indicates whether the value is a known member of the FormatParam enum.
func (e FormatParam) Valid() bool {
	switch e {
	case FormatParamJson:
		return true
	default:
		return false
	}
}

// Defines values for ConvertSmartParamsFormat.
const (
	ConvertSmartParamsFormatJson ConvertSmartParamsFormat = "json"
)

// Valid indicates whether the value is a known member of the ConvertSmartParamsFormat enum.
func (e ConvertSmartParamsFormat) Valid() bool {
	switch e {
	case ConvertSmartParamsFormatJson:
		return true
	default:
		return false
	}
}

// Defines values for ConvertOdsToXlsxParamsFormat.
const (
	ConvertOdsToXlsxParamsFormatJson ConvertOdsToXlsxParamsFormat = "json"
)

// Valid indicates whether the value is a known member of the ConvertOdsToXlsxParamsFormat enum.
func (e ConvertOdsToXlsxParamsFormat) Valid() bool {
	switch e {
	case ConvertOdsToXlsxParamsFormatJson:
		return true
	default:
		return false
	}
}

// Defines values for ConvertXlsbToXlsxParamsFormat.
const (
	ConvertXlsbToXlsxParamsFormatJson ConvertXlsbToXlsxParamsFormat = "json"
)

// Valid indicates whether the value is a known member of the ConvertXlsbToXlsxParamsFormat enum.
func (e ConvertXlsbToXlsxParamsFormat) Valid() bool {
	switch e {
	case ConvertXlsbToXlsxParamsFormatJson:
		return true
	default:
		return false
	}
}

// Defines values for ConvertXlsxToOdsParamsFormat.
const (
	Json ConvertXlsxToOdsParamsFormat = "json"
)

// Valid indicates whether the value is a known member of the ConvertXlsxToOdsParamsFormat enum.
func (e ConvertXlsxToOdsParamsFormat) Valid() bool {
	switch e {
	case Json:
		return true
	default:
		return false
	}
}

// ConvertRequest defines model for ConvertRequest.
type ConvertRequest struct {
	// File Base64-encoded spreadsheet file content
	File []byte `json:"file"`

	// Filename Original filename with extension. Required when using the smart
	// `/api/convert` endpoint so the server can infer the source format.
	Filename *string `json:"filename,omitempty"`
}

// ConvertResponse defines model for ConvertResponse.
type ConvertResponse struct {
	ContentType string `json:"content_type"`

	// Data Base64-encoded converted file content
	Data     []byte `json:"data"`
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	Success  bool   `json:"success"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	// File Spreadsheet file to convert
	File openapi_types.File `json:"file"`
}

// FormatParam defines model for FormatParam.
type FormatParam string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// ConvertSmartParams defines parameters for ConvertSmart.
type ConvertSmartParams struct {
	// Format Force a JSON response envelope even for multipart uploads
	Format *ConvertSmartParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ConvertSmartParamsFormat defines parameters for ConvertSmart.
type ConvertSmartParamsFormat string

// ConvertOdsToXlsxParams defines parameters for ConvertOdsToXlsx.
type ConvertOdsToXlsxParams struct {
	// Format Force a JSON response envelope even for multipart uploads
	Format *ConvertOdsToXlsxParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ConvertOdsToXlsxParamsFormat defines parameters for ConvertOdsToXlsx.
type ConvertOdsToXlsxParamsFormat string

// ConvertXlsbToXlsxParams defines parameters for ConvertXlsbToXlsx.
type ConvertXlsbToXlsxParams struct {
	// Format Force a JSON response envelope even for multipart uploads
	Format *ConvertXlsbToXlsxParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ConvertXlsbToXlsxParamsFormat defines parameters for ConvertXlsbToXlsx.
type ConvertXlsbToXlsxParamsFormat string

// ConvertXlsxToOdsParams defines parameters for ConvertXlsxToOds.
type ConvertXlsxToOdsParams struct {
	// Format Force a JSON response envelope even for multipart uploads
	Format *ConvertXlsxToOdsParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ConvertXlsxToOdsParamsFormat defines parameters for ConvertXlsxToOds.
type ConvertXlsxToOdsParamsFormat string

// ConvertSmartJSONRequestBody defines body for ConvertSmart for application/json ContentType.
type ConvertSmartJSONRequestBody = ConvertRequest

// ConvertSmartMultipartRequestBody defines body for ConvertSmart for multipart/form-data ContentType.
type ConvertSmartMultipartRequestBody = UploadRequest

// ConvertOdsToXlsxJSONRequestBody defines body for ConvertOdsToXlsx for application/json ContentType.
type ConvertOdsToXlsxJSONRequestBody = ConvertRequest

// ConvertOdsToXlsxMultipartRequestBody defines body for ConvertOdsToXlsx for multipart/form-data ContentType.
type ConvertOdsToXlsxMultipartRequestBody = UploadRequest

// ConvertXlsbToXlsxJSONRequestBody defines body for ConvertXlsbToXlsx for application/json ContentType.
type ConvertXlsbToXlsxJSONRequestBody = ConvertRequest

// ConvertXlsbToXlsxMultipartRequestBody defines body for ConvertXlsbToXlsx for multipart/form-data ContentType.
type ConvertXlsbToXlsxMultipartRequestBody = UploadRequest

// ConvertXlsxToOdsJSONRequestBody defines body for ConvertXlsxToOds for application/json ContentType.
type ConvertXlsxToOdsJSONRequestBody = ConvertRequest

// ConvertXlsxToOdsMultipartRequestBody defines body for ConvertXlsxToOds for multipart/form-data ContentType.
type ConvertXlsxToOdsMultipartRequestBody = UploadRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ConvertSmartWithBody request with any body
	ConvertSmartWithBody(ctx context.Context, params *ConvertSmartParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConvertSmart(ctx context.Context, params *ConvertSmartParams, body ConvertSmartJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConvertOdsToXlsxWithBody request with any body
	ConvertOdsToXlsxWithBody(ctx context.Context, params *ConvertOdsToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConvertOdsToXlsx(ctx context.Context, params *ConvertOdsToXlsxParams, body ConvertOdsToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConvertXlsbToXlsxWithBody request with any body
	ConvertXlsbToXlsxWithBody(ctx context.Context, params *ConvertXlsbToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConvertXlsbToXlsx(ctx context.Context, params *ConvertXlsbToXlsxParams, body ConvertXlsbToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConvertXlsxToOdsWithBody request with any body
	ConvertXlsxToOdsWithBody(ctx context.Context, params *ConvertXlsxToOdsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ConvertXlsxToOds(ctx context.Context, params *ConvertXlsxToOdsParams, body ConvertXlsxToOdsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Healthz request
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthzHead request
	HealthzHead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ConvertSmartWithBody(ctx context.Context, params *ConvertSmartParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertSmartRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertSmart(ctx context.Context, params *ConvertSmartParams, body ConvertSmartJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertSmartRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertOdsToXlsxWithBody(ctx context.Context, params *ConvertOdsToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertOdsToXlsxRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertOdsToXlsx(ctx context.Context, params *ConvertOdsToXlsxParams, body ConvertOdsToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertOdsToXlsxRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertXlsbToXlsxWithBody(ctx context.Context, params *ConvertXlsbToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertXlsbToXlsxRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertXlsbToXlsx(ctx context.Context, params *ConvertXlsbToXlsxParams, body ConvertXlsbToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertXlsbToXlsxRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertXlsxToOdsWithBody(ctx context.Context, params *ConvertXlsxToOdsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertXlsxToOdsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConvertXlsxToOds(ctx context.Context, params *ConvertXlsxToOdsParams, body ConvertXlsxToOdsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConvertXlsxToOdsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthzHead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzHeadRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewConvertSmartRequest calls the generic ConvertSmart builder with application/json body
func NewConvertSmartRequest(server string, params *ConvertSmartParams, body ConvertSmartJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConvertSmartRequestWithBody(server, params, "application/json", bodyReader)
}

// NewConvertSmartRequestWithBody generates requests for ConvertSmart with any type of body
func NewConvertSmartRequestWithBody(server string, params *ConvertSmartParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/convert")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConvertOdsToXlsxRequest calls the generic ConvertOdsToXlsx builder with application/json body
func NewConvertOdsToXlsxRequest(server string, params *ConvertOdsToXlsxParams, body ConvertOdsToXlsxJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConvertOdsToXlsxRequestWithBody(server, params, "application/json", bodyReader)
}

// NewConvertOdsToXlsxRequestWithBody generates requests for ConvertOdsToXlsx with any type of body
func NewConvertOdsToXlsxRequestWithBody(server string, params *ConvertOdsToXlsxParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/convert/ods-to-xlsx")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConvertXlsbToXlsxRequest calls the generic ConvertXlsbToXlsx builder with application/json body
func NewConvertXlsbToXlsxRequest(server string, params *ConvertXlsbToXlsxParams, body ConvertXlsbToXlsxJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConvertXlsbToXlsxRequestWithBody(server, params, "application/json", bodyReader)
}

// NewConvertXlsbToXlsxRequestWithBody generates requests for ConvertXlsbToXlsx with any type of body
func NewConvertXlsbToXlsxRequestWithBody(server string, params *ConvertXlsbToXlsxParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/convert/xlsb-to-xlsx")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConvertXlsxToOdsRequest calls the generic ConvertXlsxToOds builder with application/json body
func NewConvertXlsxToOdsRequest(server string, params *ConvertXlsxToOdsParams, body ConvertXlsxToOdsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConvertXlsxToOdsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewConvertXlsxToOdsRequestWithBody generates requests for ConvertXlsxToOds with any type of body
func NewConvertXlsxToOdsRequestWithBody(server string, params *ConvertXlsxToOdsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/convert/xlsx-to-ods")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthzRequest generates requests for Healthz
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthzHeadRequest generates requests for HealthzHead
func NewHealthzHeadRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodHead, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ConvertSmartWithBodyWithResponse request with any body
	ConvertSmartWithBodyWithResponse(ctx context.Context, params *ConvertSmartParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertSmartResponse, error)

	ConvertSmartWithResponse(ctx context.Context, params *ConvertSmartParams, body ConvertSmartJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertSmartResponse, error)

	// ConvertOdsToXlsxWithBodyWithResponse request with any body
	ConvertOdsToXlsxWithBodyWithResponse(ctx context.Context, params *ConvertOdsToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertOdsToXlsxResponse, error)

	ConvertOdsToXlsxWithResponse(ctx context.Context, params *ConvertOdsToXlsxParams, body ConvertOdsToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertOdsToXlsxResponse, error)

	// ConvertXlsbToXlsxWithBodyWithResponse request with any body
	ConvertXlsbToXlsxWithBodyWithResponse(ctx context.Context, params *ConvertXlsbToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertXlsbToXlsxResponse, error)

	ConvertXlsbToXlsxWithResponse(ctx context.Context, params *ConvertXlsbToXlsxParams, body ConvertXlsbToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertXlsbToXlsxResponse, error)

	// ConvertXlsxToOdsWithBodyWithResponse request with any body
	ConvertXlsxToOdsWithBodyWithResponse(ctx context.Context, params *ConvertXlsxToOdsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertXlsxToOdsResponse, error)

	ConvertXlsxToOdsWithResponse(ctx context.Context, params *ConvertXlsxToOdsParams, body ConvertXlsxToOdsJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertXlsxToOdsResponse, error)

	// HealthzWithResponse request
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error)

	// HealthzHeadWithResponse request
	HealthzHeadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHeadResponse, error)
}

type ConvertSmartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConvertResponse
	JSON400      *BadRequest
	JSON415      *UnsupportedMediaType
	JSON422      *UnprocessableEntity
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r ConvertSmartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConvertSmartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConvertSmartResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ConvertOdsToXlsxResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConvertResponse
	JSON400      *BadRequest
	JSON415      *UnsupportedMediaType
	JSON422      *UnprocessableEntity
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r ConvertOdsToXlsxResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConvertOdsToXlsxResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConvertOdsToXlsxResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ConvertXlsbToXlsxResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConvertResponse
	JSON400      *BadRequest
	JSON415      *UnsupportedMediaType
	JSON422      *UnprocessableEntity
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r ConvertXlsbToXlsxResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConvertXlsbToXlsxResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConvertXlsbToXlsxResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ConvertXlsxToOdsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConvertResponse
	JSON400      *BadRequest
	JSON415      *UnsupportedMediaType
	JSON422      *UnprocessableEntity
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r ConvertXlsxToOdsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConvertXlsxToOdsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConvertXlsxToOdsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthzHeadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HealthzHeadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzHeadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzHeadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ConvertSmartWithBodyWithResponse request with arbitrary body returning *ConvertSmartResponse
func (c *ClientWithResponses) ConvertSmartWithBodyWithResponse(ctx context.Context, params *ConvertSmartParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertSmartResponse, error) {
	rsp, err := c.ConvertSmartWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertSmartResponse(rsp)
}

func (c *ClientWithResponses) ConvertSmartWithResponse(ctx context.Context, params *ConvertSmartParams, body ConvertSmartJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertSmartResponse, error) {
	rsp, err := c.ConvertSmart(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertSmartResponse(rsp)
}

// ConvertOdsToXlsxWithBodyWithResponse request with arbitrary body returning *ConvertOdsToXlsxResponse
func (c *ClientWithResponses) ConvertOdsToXlsxWithBodyWithResponse(ctx context.Context, params *ConvertOdsToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertOdsToXlsxResponse, error) {
	rsp, err := c.ConvertOdsToXlsxWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertOdsToXlsxResponse(rsp)
}

func (c *ClientWithResponses) ConvertOdsToXlsxWithResponse(ctx context.Context, params *ConvertOdsToXlsxParams, body ConvertOdsToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertOdsToXlsxResponse, error) {
	rsp, err := c.ConvertOdsToXlsx(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertOdsToXlsxResponse(rsp)
}

// ConvertXlsbToXlsxWithBodyWithResponse request with arbitrary body returning *ConvertXlsbToXlsxResponse
func (c *ClientWithResponses) ConvertXlsbToXlsxWithBodyWithResponse(ctx context.Context, params *ConvertXlsbToXlsxParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertXlsbToXlsxResponse, error) {
	rsp, err := c.ConvertXlsbToXlsxWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertXlsbToXlsxResponse(rsp)
}

func (c *ClientWithResponses) ConvertXlsbToXlsxWithResponse(ctx context.Context, params *ConvertXlsbToXlsxParams, body ConvertXlsbToXlsxJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertXlsbToXlsxResponse, error) {
	rsp, err := c.ConvertXlsbToXlsx(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertXlsbToXlsxResponse(rsp)
}

// ConvertXlsxToOdsWithBodyWithResponse request with arbitrary body returning *ConvertXlsxToOdsResponse
func (c *ClientWithResponses) ConvertXlsxToOdsWithBodyWithResponse(ctx context.Context, params *ConvertXlsxToOdsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConvertXlsxToOdsResponse, error) {
	rsp, err := c.ConvertXlsxToOdsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertXlsxToOdsResponse(rsp)
}

func (c *ClientWithResponses) ConvertXlsxToOdsWithResponse(ctx context.Context, params *ConvertXlsxToOdsParams, body ConvertXlsxToOdsJSONRequestBody, reqEditors ...RequestEditorFn) (*ConvertXlsxToOdsResponse, error) {
	rsp, err := c.ConvertXlsxToOds(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConvertXlsxToOdsResponse(rsp)
}

// HealthzWithResponse request returning *HealthzResponse
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzResponse(rsp)
}

// HealthzHeadWithResponse request returning *HealthzHeadResponse
func (c *ClientWithResponses) HealthzHeadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHeadResponse, error) {
	rsp, err := c.HealthzHead(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzHeadResponse(rsp)
}

// ParseConvertSmartResponse parses an HTTP response from a ConvertSmartWithResponse call
func ParseConvertSmartResponse(rsp *http.Response) (*ConvertSmartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConvertSmartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConvertResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest UnsupportedMediaType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) unsupported

	}

	return response, nil
}

// ParseConvertOdsToXlsxResponse parses an HTTP response from a ConvertOdsToXlsxWithResponse call
func ParseConvertOdsToXlsxResponse(rsp *http.Response) (*ConvertOdsToXlsxResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConvertOdsToXlsxResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConvertResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest UnsupportedMediaType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) unsupported

	}

	return response, nil
}

// ParseConvertXlsbToXlsxResponse parses an HTTP response from a ConvertXlsbToXlsxWithResponse call
func ParseConvertXlsbToXlsxResponse(rsp *http.Response) (*ConvertXlsbToXlsxResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConvertXlsbToXlsxResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConvertResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest UnsupportedMediaType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) unsupported

	}

	return response, nil
}

// ParseConvertXlsxToOdsResponse parses an HTTP response from a ConvertXlsxToOdsWithResponse call
func ParseConvertXlsxToOdsResponse(rsp *http.Response) (*ConvertXlsxToOdsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConvertXlsxToOdsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConvertResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest UnsupportedMediaType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableEntity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/vnd.oasis.opendocument.spreadsheet) unsupported

	}

	return response, nil
}

// ParseHealthzResponse parses an HTTP response from a HealthzWithResponse call
func ParseHealthzResponse(rsp *http.Response) (*HealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHealthzHeadResponse parses an HTTP response from a HealthzHeadWithResponse call
func ParseHealthzHeadResponse(rsp *http.Response) (*HealthzHeadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzHeadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FnvbhO7En8Vy/dKQLVNQikIrXR11VKu2is4QaRIlWh14qwnjWHXXmxvm4AinU/nAY7OE/IkRzP2JrtJ",
	"oIGDQDr0S7t/xjPjmfn9Ztb5wDNTlEaD9o6nH3gprCjAg6W7/xlbCP8Cn+GtBJdZVXplNE/xZQZMsP8P",
	"+r8wC6402gEDfQW5KYHBFWg2NpYVVe5VKaxnVZkbIR1PuEIF7yqwM55wLQrgKR+TMZ5wl02gEGgQdFXw",
	"9DV/44zmFwn3sxIlnbdKX/L5fJ7w2jD5eyjkS3hXgfN4lxntQdOlKMtcZQI975Ky9EPDzL8tjHnK/9Vd",
	"xqIb3rruU2uNfRmNBJPtMBwKyWwwyj7+9icrlHNKXzJjmdJXIleSKV1Wns8TfqI9WC1yUvr9XKzNMgf2",
	"CiwDMj9P+CtdWpOBc2KUw1PtlZ99P6+eqZGF/nisMmCZ0VdgnTKajYXKQQbvXFWWxnqQz0EqcUrZ/17u",
	"NayzscqBxfpEyagEbTwhz32j7EprSrBehZLEpevYORQOHu3vgs6MBMlcaUFINwHwwVa9xaRGRcpHMw98",
	"DQIJGQgIWjXSt+pSYdprEXat/ITB1IPGUHcYeq0sSHY9Ac0qqls/AeYKYf25HnZFqbohN37IQMvSKO2Z",
	"M0EqVFMmNFN6DDY8NBXSQnC7c655wmEqihKjwC1gQDvT3I3Wt0JgDv4g5ilwS8yb0RvICESLiMfcrYU8",
	"Bu9XH+tlab9ZLldadkwJelrkwVm3a6gYpcmqArTvNLJS5B36vykBUnhxY4ZjEOta+sr8borkdNMip963",
	"F+z19h/3GtaU9o/2lyuV9nAJxAmuypARWqu9rWAhOzImB6HXElYvbLictHMR/Yoh25TbNirXMgs1by4D",
	"UdPtHTR6h+qOjRXk8sYCC8o2efGK+tQXQnqwimFv6qy30qy0oK73VdWPYkqPzbr549PTF+zgxQm13GgX",
	"47JKLY6NwF8DaHb2bHCY4N+zhAktWf9oEGHrOuf6lQPHmhStNJuAkDk4xwojoWEIyQTXnOudnRPsdbWe",
	"dGeHDQnuwyRcTOnCSDcM4oMFxzZUpTs753qXHGQff/+DfIwPzuhB/2iA9+hxQwD1xaSRh7We4WIC6aJf",
	"u1h9Q+rVIRkhXWE4SZgFX1ntiMxWUCscE0yaa42SpHm1/0S1bexT+0+YyK/FzC3049iEOg6kZMP/hoD9",
	"J+gwlg0PsgxKn7J1C95geJej12LiMroxa8WRxBED5yqDCKg4bD0/OcVK98oTimKOI7WCxUriCY8J4Sm/",
	"3+l1ergCKVOUiqf8QafXecATXgo/IVw0uwWhxgT0tAv1CDxk3oWoxEJhY2sKiviiVS26FNVm1OqYqLwp",
	"hFeZyPNZSjkI9cW6sa6oIGKtLd5P68eh8jjtw1JUTyRP654ywL5HW1pOwa83zxFLkW5zSp5fBByD84dG",
	"frtpamXMQB7YUNXb62tT3LxNP0j3q6P1Xq/37TezmL6S9dYsnHLUoDf147atbcj177f+LzS5NlA+aZPJ",
	"3Ug+NZ8g6lt4vodw2w9h3xTNRXq6jc8eXHL/4c1LNs7WuHhvb5vF658N84Q/3MbX9icQDdNVUWAIU07w",
	"q7HO7iLWdyXRReSJexhncYmo5DXRXKCOJvV0jXS73uzSbNSgoY2I70t3as7CFHWL+h+P+h+ISpouaO76",
	"2XAXY0DzVD1ObYU07LxbQ+0sd6NbrN1i7RZriLXWx822YJsi2Ix022Btemr6dNZ6C7V/2DD7GVzRN/xP",
	"DqvFEcEnUTUBkfvJe7R4CRtAdBzf31g1Hqa+W+ZCrdTL8njKvN0mgYNwkqocC67NVnYXHGLZBLK3jV0F",
	"YX4xT/BSfnIjx/hy82a+3g929/jpwRGdd2jDRkbO7m1yjRSQ2kA/K78BmEzkTAJ98SAu4qEyT3hlc57y",
	"ifdl2u3mKDcxzqePe497REzR0ueO4ZZHSstfmepKmCdrJ2jtIEf5uJH5xfyvAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
